#!/usr/bin/php
<?php
/************************************************************************
 Copyright 2025 Henrik Carlqvist

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 This file is distributed with obis2snmp.

 As obis2snmp is free software you can redistribute this file and/or
 modify it under the terms of the 2 clause BSD license.

 SPDX-License-Identifier: BSD-2-Clause

*************************************************************************/

$version = "0.0.1";
$timeout = 500000;

function sanitize_string($data)
{
  $data = str_replace("\r", " ", str_replace("\n", " ", $data));
  $out=$data;
  for($i=0; $i<strlen($data); $i++)
  {
    if((ord($data[$i])>=127)||(ord($data[$i])<32))
    {
      $data=$out;
      $len = strlen($data);
      $out="";
      for($i=0; $i<$len; $i++)
      {
        $out .= sprintf("%02X", ord($data));
        $data = substr($data, 1);
      }
      break;
    }
  }
  return $out;
}

function snmp2string($data)
{
  if(!strncmp("Hex-STRING: ", $data, 12))
    $out = str_replace(" ", "", substr($data, 12));
  else
    $out = sanitize_string(
              str_replace("\"", "",
                          str_replace("STRING: ", "",
                              str_replace("INTEGER: ", "",
                                  str_replace("Gauge32: ", "", $data)))));
  return $out;
} /* snmp2string */

function fix_snmp_array(&$data)
{
  $data =  snmp2string($data);
} /* fix_snmp_array */

function oid_index($oid)
{
   return substr(strrchr($oid, '.'),1);
}

function host_data($metertype, $multiplier, $descriptions, $units, $values)
{
  if($metertype && $multiplier && $descriptions && $units && $values)
  {
    array_walk($metertype, 'fix_snmp_array');
    array_walk($multiplier, 'fix_snmp_array');
    array_walk($descriptions, 'fix_snmp_array');
    array_walk($units, 'fix_snmp_array');
    array_walk($values, 'fix_snmp_array');

    foreach($metertype as $key => $meter)
    {
      if(!strncmp($meter, "TEMP", 4))
      {
        $meter_index=oid_index($key);
        $meter_multiplier=1;
        foreach($multiplier as $key2 => $divisor)
        {
          if($meter_index == oid_index($key2))
          $meter_multiplier = $divisor;
        }
        foreach($descriptions as $key2 => $description)
        {
          if($meter_index == oid_index($key2))
          {
             $label[] = $description;
          }
        }
        foreach($units as $key2 => $u)
        {
          if($meter_index == oid_index($key2))
          {
             $unit[] = $u;
          }
        }
        foreach($values as $key2 => $v)
        {
          if($meter_index == oid_index($key2))
          {
             $value[] = $v/$meter_multiplier;
          }
        }
        $arr = array('label' => $label,
                     'value' => $value,
                     'unit' => $unit);
        if((count($label)==count($value)) && (count($label)==count($unit)))
          return $arr;
      }
    }
  }
  return false;
} /* host_data */

if (($_SERVER["argc"] < 2)||($_SERVER["argv"][1]=="-h")||($_SERVER["argv"][1]=="-v")||
    ($_SERVER["argv"][1]=="--help")||($_SERVER["argv"][1]=="--version"))
{
   printf("snmpobistemp version %s\n", $version);
   printf(
      "Usage: %s [option...] <host> [host...]\n",
      $_SERVER["argv"][0]);
   printf("  -c community      SNMP community, with multiple -c multiple\n" .
	  "                    communities will be searched for each host.\n");
   printf("  -t timeout        SNMP timeout in us, default 500000 us (0.5 s).\n");
   printf("  -l label=replace  Replace a label with another text\n");
   printf("  -s separator      Separator between label and value, default newline\n");
   printf("  -p seconds        Seconds to pause between each sample, will daemonize\n");
   printf("  -z                Writes \"\\e[H\\e[J\" to clear terminal\n");
   printf("  -o file           Redirect output to file or device instead of stdout\n");
   printf("  -h                Shows this help.\n");
   return 1;
}
else
{
  $separator="\n";
  $bCommunity=false;
  $bTimeOut=false;
  $bSeparator=false;
  $bReplaceLabel=false;
  $bPause=false;
  $bClearTerminal=false;
  $bRedirect=false;
  /* Avoid warnings from snmp */
  error_reporting(E_ERROR | E_PARSE);
  
  for($i=1; $i<$_SERVER["argc"]; $i++)
  {
    if($bCommunity)
    {
      $Communities[] = $_SERVER["argv"][$i];
      $bCommunity = false;
    }
    else if($bTimeOut)
    {
      $timeout = $_SERVER["argv"][$i];
      $bTimeOut = false;
    }
    else if($bSeparator)
    {
      $separator = $_SERVER["argv"][$i];
      $bSeparator = false;
    }
    else if($bReplaceLabel)
    {
      $replacement = explode("=", $_SERVER["argv"][$i]);
      if(count($replacement) == 2)
      {
        $replacements[$replacement[0]] = $replacement[1];
      }
      $bReplaceLabel=false;
    }
    else if($bPause)
    {
      $pause = $_SERVER["argv"][$i];
      $bPause = false;
    }
    else if($bRedirect)
    {
      fclose(STDOUT);
      $STDOUT = fopen($_SERVER["argv"][$i], 'wb');
      $bRedirect = false;
    }
    else
    {
      if($_SERVER["argv"][$i]=="-c")
      {
	$bCommunity = true;
      }
      else if($_SERVER["argv"][$i]=="-t")
      {
	$bTimeOut = true;
      }
      else if($_SERVER["argv"][$i]=="-s")
      {
	$bSeparator = true;
      }
      else if($_SERVER["argv"][$i]=="-l")
      {
	$bReplaceLabel = true;
      }
      else if($_SERVER["argv"][$i]=="-p")
      {
	$bPause = true;
        if(pcntl_fork() > 0)
          return;
      }
      else if($_SERVER["argv"][$i]=="-z")
      {
	$bClearTerminal = true;
      }
      else if($_SERVER["argv"][$i]=="-o")
      {
	$bRedirect = true;
      }
      else
      {
	$HostsToSearch[] = $_SERVER["argv"][$i];
      }
    }
  }
  $Communities[] = "public";
  if(!isset($HostsToSearch))
  {
    printf("Usage: %s [options] [-c community] <host> [host...]\n", $_SERVER["argv"][0]);
    printf("At least one host must be given!\n");
    printf("Use -h to get help about more options.\n");
    return 2;
  }
  $HostsToSearch = array_values(array_unique($HostsToSearch));
  for($i=0; $i<count($Communities); $i++)
  {
    /* printf("Community: %s\n", $Communities[$i]); */
  }
  snmp_set_valueretrieval(SNMP_VALUE_LIBRARY);
  snmp_set_oid_output_format(SNMP_OID_OUTPUT_NUMERIC);
  do
  {
    for($i=0; $i<count($HostsToSearch); $i++)
    {
      $current_host_found=FALSE;
      for($j=0; $j<count($Communities); $j++)
      {
        $new_host =
          host_data(snmp2_real_walk($HostsToSearch[$i],
                                    $Communities[$j],
                                    ".1.3.6.1.4.1.62368.1.1.2",
                                    $timeout, 3),
		    snmp2_real_walk($HostsToSearch[$i],
		            	    $Communities[$j],
				    ".1.3.6.1.4.1.62368.1.1.6",
				    $timeout, 3),
		    snmp2_real_walk($HostsToSearch[$i],
			  	    $Communities[$j],
				    ".1.3.6.1.4.1.62368.1.1.7.0",
				    $timeout, 3),
		    snmp2_real_walk($HostsToSearch[$i],
				    $Communities[$j],
				    ".1.3.6.1.4.1.62368.1.1.8.0",
				    $timeout, 3),
		    snmp2_real_walk($HostsToSearch[$i],
				    $Communities[$j],
        		            ".1.3.6.1.4.1.62368.1.1.10.0",
			            $timeout, 3)
                    );
        if($new_host)
        {
          $maxlabellen=0;
          foreach($new_host['label'] as $key => $label)
          {
            if(isset($replacements[$label]))
              $new_host['label'][$key]=$replacements[$label];
          }
          foreach($new_host['label'] as $label)
          {
            if(strlen($label) > $maxlabellen)
              $maxlabellen = strlen($label);
          }
          if($bClearTerminal)
            printf("\e[H\e[J");
          foreach($new_host['label'] as $key => $label)
          {
            printf("%-".$maxlabellen."s".$separator."%6.2f %s\n",
                   $label, $new_host['value'][$key], $new_host['unit'][$key]);
          }
        }
      }
      if(isset($pause))
        sleep($pause);
    }
  } while($pause);
}
?>
